baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

[params]
  [params.author]
    name = "Your Name"
    description = "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat."
    image = "https://domain.com/profile.png"
  [params.social]
    github = "https://github.com/username"
    gitlab = "https://github.com/username"
    telegram = "https://t.me/username"
    linkedin = "https://linkedin.com/in/username"
    email = "mailto:email@domain.com"
